Rama2
Iker-elorrieta/ADT3 pull request #2
Opened 2021-11-02 08:24 UTC by Asierhernandezga

Tenemos algún fallo a la hora de leer el fichero.dat ya que lee solo el primer libro y a la hora de escribir en el los ficheros en general ya que no comprueba del todo que ya exista

2021-11-02 11:18 UTC, Iker-elorrieta requested changes
![image](https://user-images.githubusercontent.com/71759245/139836677-1bdd695e-ccb1-4d63-a47a-26898788c349.png)
Solo me lee un libro, el código no es el óptimo.

El tema de la escritura de nuevos libros hay que replantearlo. Hay errores en la lectura del dat
Algunos teses fallan:

![image](https://user-images.githubusercontent.com/71759245/139836865-43e6f711-4f3a-4959-ac36-8039e0b4ff4c.png)

Sigue habiendo String puestos a pelo

2021-11-02 11:18 UTC, Iker-elorrieta commented on RetoBiblioteca/src/RetoBiblioteca/EscribirXML.java
> +				Element miLibro = doc.createElement("LIBRO");
Sigue habiendo strings sueltos

2021-11-02 23:15 UTC, Asierhernandezga commented on RetoBiblioteca/src/RetoBiblioteca/EscribirXML.java
> +				Element miLibro = doc.createElement("LIBRO");
Corregido, creo que ya están todos los que te refieres además de alguno extra.

2021-11-02 23:18 UTC, Asierhernandezga commented
Ya se ha corregido el tema de que solo leyese un libro, el tema de escritura de los libros esta cambiada, la lectura del .dat ya funciona correctamente, todos los test han sido modificados y funcionan correctamente tanto en Windows como en Unix, se han eliminado todo los Strings sueltos que había además de que se ha creado un método nuevo para optimizar el tema de la escritura y se ha optimizado el código. Carga los datos de los libros nada mas abrir el programa para su posterior uso

2021-11-05 07:12 UTC, Iker-elorrieta requested changes
Si se introduce un nuevo libro igual que a uno anterior, lo mete igualmente.
Se ha perdido la funcionalidad de cargar libros desde cualquiera de los tres archivos (Tiene que poder hacerse lo del sprint1)
Lo demás parece que funciona correctamente, esto es, el insertado y volcado en cualquiera de los 3 formatos.

2021-11-05 07:12 UTC, Iker-elorrieta commented on RetoBiblioteca/src/Escribir/EscribirTXT.java
> +				while ((linea = fichero.readLine()) != null) {
Esta parte no está probada

2021-11-05 08:30 UTC, Iker-elorrieta approved these changes
Falta mejorar algo el test que no cubre una parte del código. Tenéis que cambiar el código de esa función.

2021-11-05 08:30 UTC, Iker-elorrieta commented on RetoBiblioteca/src/Leer/LeerTXT.java
> +				} else {
En las pruebas no se entra a este "else". Sigue siendo un código no optimo con el tokens.countTokens() == 6, en el siguiente sprint tiene que estar cambiado.

2021-11-05 08:30 UTC, merged

2021-11-05 08:32 UTC, Asierhernandezga commented on RetoBiblioteca/src/Leer/LeerTXT.java
> +				} else {
De acuerdo