Rama3
Iker-elorrieta/ADT3 pull request #3
Opened 2021-11-09 08:39 UTC by Asierhernandezga

Pull Request

2021-11-09 08:42 UTC, Asierhernandezga commented
Hacemos el pull request, faltan test por probar que no nos ha dado por falta de tiempo, y cambiar lo del StringTokenizer

2021-11-09 12:43 UTC, Iker-elorrieta requested changes
Faltan muchas partes del menú por probar.
Solo se utiliza un contains en las búsquedas individuales por atributo.
La busqueda no hace > o < para paginas o altura..

2021-11-09 12:43 UTC, Iker-elorrieta commented on RetoBiblioteca/src/RetoBiblioteca/Menu.java
> +			if (miString.contains("[")) {
No se combinan búsquedas, solo admite una de ellas

2021-11-09 12:43 UTC, Iker-elorrieta commented on RetoBiblioteca/src/RetoBiblioteca/Menu.java
> +			} else if (miString.contains("?")) {
final string!

2021-11-12 09:51 UTC, IsaiahQuintana24 commented on RetoBiblioteca/src/RetoBiblioteca/Menu.java
> +			if (miString.contains("[")) {
Corregido

2021-11-12 09:52 UTC, IsaiahQuintana24 commented on RetoBiblioteca/src/RetoBiblioteca/Menu.java
> +			} else if (miString.contains("?")) {
Corregido

2021-11-12 14:50 UTC, Asierhernandezga commented
Creemos que ya están todos los test, además de que ya están cambiados los final String.
También se ha añadido al principio la opción de si quieres cargar todos los textos en el array, ya funciona las búsquedas de < o >.
También se pueden combinar búsquedas, **Ej: [?El**

2021-11-15 07:38 UTC, Iker-elorrieta requested changes
![image](https://user-images.githubusercontent.com/71759245/141740963-2a3da548-2861-4a95-805e-813926be60f4.png)
No funciona como debería?

2021-11-16 07:56 UTC, Iker-elorrieta requested changes
![image](https://user-images.githubusercontent.com/71759245/141943822-e330438e-cb96-4417-b387-8bd102b89ed1.png)
Falla en lo mismo, o no está bien explicado o no se ha entendido el error previo.

2021-11-16 08:39 UTC, merged